### ISSUE TITLE
Feature request – restrict by category

### ISSUE THREAD

**Issue by michaelphilipsmith** [theukedge/recent-contributors-widget#5]
It would be a great addition to this plugin to also be able to restrict by category. So on the blog archive page for the category 'Biscuits', it only shows the recent contributors whose posts were categorised as 'Biscuits' . Does that make sense? Apologies if the issue area is not the right place for feature requests! Thanks!

**Comment by theukedge** [comment]
Hi Michael, thanks for your suggestion. This is _absolutely_ the right place for it!

Let's do something about how we could implement this if we were going to:

- We can't enable it by default: there'll definitely be people who want to show posts of recent contributors from across the site, regardless of whether they're viewing a particular category or not.
- I could add a setting to the widget, but if you have lots of categories and want to show only the posts from each category while viewing that category, you'd have to duplicate the widget hundreds (thousands?) of times and use something like Jetpack's Widget Visibility to only show the right widget on each category
- or, add an option to "limit posts by current category" which automatically checks whether a specific category is being viewed and if so, limits the results to posts sitting in that category?

What do you think? How would you like to use it?

**Comment by michaelphilipsmith** [comment]
The second suggestion would be fine for my use case as I only want it to appear in a couple of places and already have Widget Logic up and running, but in the interest of the plugin I would assume the second is probably simpler to implement and would be more useful for more people!

**Comment by theukedge** [comment]
Because this is something of an edge case, I think the best approach is to add a filter to the args for WP_Query so that you can get the custom queries that you're looking while not adding unnecessary settings and further enabling other users to get the custom results that they desire. I've opened up #6 for this purpose.
